name: groupup
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.3+23

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  fl_chart: ^0.55.2
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  share_plus: ^6.3.0
  sign_in_with_apple: ^4.3.0
  flutter_svg: ^1.1.6
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.0
  firebase_dynamic_links: ^5.0.11
  firebase_storage: ^11.0.10
  provider: ^6.0.5
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6+1
  google_sign_in: ^5.4.2
  cached_network_image: ^3.2.3
  currency_picker: ^2.0.14
  pinput: ^2.2.23
  url_launcher: ^6.1.8
  ntp: ^2.0.0
  story: ^1.0.0+1
  sentry_flutter: ^6.18.3
  intl_phone_field: ^3.1.0
  screenshot: ^1.3.0
  path_provider: ^2.0.12
  cloud_functions: ^4.0.7
  flutter_stripe: ^8.0.0+1
  uni_links: ^0.5.1
  shared_preferences: ^2.0.17
  mixpanel_flutter: ^2.0.0
  firebase_remote_config: ^3.0.13
  package_info_plus: ^3.0.3
  rive: ^0.10.3

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
      image_path: "assets/icons/groupup_icon.png"
      android: true
      ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
     - family: Montserrat-Bold
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
     - family: Montserrat-SemiBold
       fonts:
         - asset: assets/fonts/Montserrat-SemiBold.ttf
     - family: Montserrat-Regular
       fonts:
         - asset: assets/fonts/Montserrat-Regular.ttf
     - family: Montserrat-Medium
       fonts:
         - asset: assets/fonts/Montserrat-Medium.ttf