import 'package:groupup/models/top_bar_individual_group.dart';

class GroupModel {
  final String title,
      image,
      rank,
      daysGone,
      daysLeft,
      rankIcon,
      daysGoneIcon,
      daysLeftIcon;

  final TopBarIndividualGroupModel topBarIndividualGroupModel;

  GroupModel({
    required this.topBarIndividualGroupModel,
    required this.title,
    required this.image,
    required this.rank,
    required this.daysGone,
    required this.daysLeft,
    required this.rankIcon,
    required this.daysGoneIcon,
    required this.daysLeftIcon,
  });
}

List groupsData = [
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "RunForestRun",
      objective: "Run more",
      reward: "100 dollars",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 10, 01),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#RunForestRun",
    image: "assets/images/runforest.png",
    rank: "3",
    daysGone: "10",
    daysLeft: "20",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "ShitProject",
      objective: "Shit more",
      reward: "50 toilet paper roll",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 09, 15),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#ShitProject",
    image: "assets/images/shitproject.png",
    rank: "8",
    daysGone: "3",
    daysLeft: "11",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "NoPainNoGain",
      objective: "Climb more stairs",
      reward: "30 dollars",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 09, 20),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#NoPainNoGain",
    image: "assets/images/nopainnogain.png",
    rank: "3",
    daysGone: "22",
    daysLeft: "5",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "FattyBelly",
      objective: "Eat more",
      reward: "10 donuts",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 10, 15),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#FattyBelly",
    image: "assets/images/fattybelly.png",
    rank: "5",
    daysGone: "38",
    daysLeft: "42",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "RunForestRun",
      objective: "Run more",
      reward: "100 dollars",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 10, 01),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#RunForestRun",
    image: "assets/images/runforest.png",
    rank: "3",
    daysGone: "10",
    daysLeft: "20",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "ShitProject",
      objective: "Shit more",
      reward: "50 toilet paper roll",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 09, 15),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#ShitProject",
    image: "assets/images/shitproject.png",
    rank: "8",
    daysGone: "3",
    daysLeft: "11",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "NoPainNoGain",
      objective: "Climb more stairs",
      reward: "30 dollars",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 09, 20),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#NoPainNoGain",
    image: "assets/images/nopainnogain.png",
    rank: "3",
    daysGone: "22",
    daysLeft: "5",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
  GroupModel(
    topBarIndividualGroupModel: TopBarIndividualGroupModel(
      title: "FattyBelly",
      objective: "Eat more",
      reward: "10 donuts",
      objectiveIcon: "assets/icons/objective.png",
      rewardIcon: "assets/icons/reward.png",
      startDate: DateTime(2022, 10, 15),
      endDate: DateTime(2022, 12, 31),
    ),
    title: "#FattyBelly",
    image: "assets/images/fattybelly.png",
    rank: "5",
    daysGone: "38",
    daysLeft: "42",
    rankIcon: "assets/icons/rank.png",
    daysGoneIcon: "assets/icons/daysgone.png",
    daysLeftIcon: "assets/icons/daysleft.png",
  ),
];
